# @package _global_

# Set of 'stable' image (images which have been tested to work together)
# and relevant dependencies which describe the conditions those images
# have been validated.

scenes:
  scene_ids:
    - clipgt-05bb8212-63e1-40a8-b4fc-3142c0e94646 # taken from huggingface
services:
  sensorsim:
    image: docker.io/carlasimulator/nvidia-nurec-grpc:0.2.0
    external_image: true
  driver:
    image: alpasim-base:0.1.4
  physics:
    image: alpasim-base:0.1.4
  runtime:
    image: alpasim-base:0.1.4
  controller:
    image: alpasim-base:0.1.4
  trafficsim:
    image: alpasim-base:0.1.4 # temporary stub
runtime:
  simulation_config:
    planner_delay_us: 0
